pagina_web/ServDjango/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

pagina_web/app/urls.py
from django.urls import path
from .import views

app_name= 'app'

urlpatterns =[
    path('Home', views.index, name='index'), #Muestra Pag Principal
    path('Home_login_post', views.Home_login_post, name='Home_login_post'), # recoje los datos del login
    path('Home_registro_post', views.Home_registro_post, name='Home_registro_post'), # Recojer los datos del formulario
    path('Consul_List_Indi_Admin', views.Consul_Lista_Individuos_Admin, name='consu'),
    path('Pag_Admin', views.Pag_Admin, name='Pag_Admin'), # Pagina inicio de sesion Admin
    path('Pag_Usu', views.Pag_Usu, name='Pag_Usu'), # Pagina inicio de sesion Usuario
    path('', views.cerrar_sesion_post, name='cerrar_sesion_post'), # Boton cerrar sesion 
    path('Actualizar_Datos_Admin', views.Actualizar_Datos_Admin, name='Actualizar_Datos_Admin'), # Boton Actualizar Datos
    path('Actualizar_Datos_Post/<int:id_usuario>', views.Actualizar_Datos_Post, name='Actualizar_Datos_Post'), # Recoje Datos para actualizar
    path('Actualizar_Datos_Usu', views.Actualizar_Datos_Usu, name='Actualizar_Datos_Usu'), # Boton Actualizar Datos
    path('Crear_Partido_Politico', views.Crear_Partido_Politico, name='Crear_Partido_Politico'), # Boton Crear Partido Politico
    path('Crear_Partido_Politico_Post/<int:id_usuario>', views.Crear_Partido_Politico_Post, name='Crear_Partido_Politico_Post'), # Recoje Los Datos 
    path('Lista_Partido/<int:id_usuario>', views.Lista_Partido, name='Lista_Partido'), # Url Lista Partidos Admin
    path('Consular_PartidoP_Usuario',views.Consutar_PartidoP_Usuario,name='Consultar_Partido_Usuario'),#Url Consultar Partido
    path('Crear_Individuo_Admin',views.Crear_Individuo_Admin,name='Crear_Individuo_Admin'),#Boton Crear Individuo
    path('Crear_Individuo_Admin_Post/<int:id_usuario>', views.Crear_Individuo_Admin_Post, name='Crear_Individuo_Admin_Post'), # Recoje Los Datos 
    path('Crear_Individuo_Usu',views.Crear_Individuo_Usu,name='Crear_Individuo_Usu'),#Boton Crear Individuo
    path('Crear_Individuo_Usu_Post/<int:id_usuario>', views.Crear_Individuo_Usu_Post, name='Crear_Individuo_Usu_Post'), # Recoje Los Datos 
    #path('Lista_Individuo_Admin/<int:id_usuario>', views.Lista_Individuo_Admin, name='Lista_Individuo_Admin'), # Url Lista idivduos Admin
    path('Crear_Proceso_Admin',views.Crear_Proceso_Admin,name='Crear_Proceso_Admin'),#Boton Crear Proceso
    path('Crear_Proceso_Admin_Post', views.Crear_Proceso_Admin_Post, name='Crear_Proceso_Admin_Post'), # Recoje Los Datos
    path('Crear_Proceso_Usu',views.Crear_Proceso_Usu,name='Crear_Proceso_Usu'),#Boton Crear Proceso
    path('Crear_Proceso_Usu_Post/<int:id_usuario>', views.Crear_Proceso_Usu_Post, name='Crear_Proceso_Usu_Post'), # Recoje Los Datos
    path('Lista_Individuos/<int:id_usuario>', views.Lista_Individuos, name='Lista_Individuos'), # Url Lista idivduos Admin
]

pagina_web/app/templates/app/Act_Datos_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Actualizar_Datos.css' %}">
{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<form action="{% url 'app:Actualizar_Datos_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Actualizar Datos</h1>
    <input type="text" placeholder="Nombres"  autocomplete="given-name" value="{{ request.user.first_name }}" name="nombres" > <br> <p></p>
    <input type="text" placeholder="Apellidos"  autocomplete="family-name" value="{{ request.user.last_name }}" name="apellidos"> <br> <p></p>
    <input type="text" placeholder="Usuario"  autocomplete="additional-name" value="{{ request.user.username }}" name="username"><br><p></p>
    <input type="password" placeholder="Nueva Contraseña" autocomplete="new-password" required name="password"> <br> <p></p>
    <input type="email" placeholder="Email" autocomplete="email" value="{{ request.user.email }}" name="email"> <br><p></p>
    <input class="form-boton" type="submit" value="Actualizar">  <br><p></p>  
    <br><p></p>            
</form>
{% endblock %}

pagina_web/app/templates/app/Actualizar_Datos_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Actualizar_Datos.css' %}">
{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<form action="{% url 'app:Actualizar_Datos_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Actualizar Datos</h1>
    <input type="text" placeholder="Nombres"  autocomplete="given-name" value="{{ request.user.first_name }}" name="nombres" > <br> <p></p>
    <input type="text" placeholder="Apellidos"  autocomplete="family-name" value="{{ request.user.last_name }}" name="apellidos"> <br> <p></p>
    <input type="text" placeholder="Usuario"  autocomplete="additional-name" value="{{ request.user.username }}" name="username"><br><p></p>
    <input type="password" placeholder="Nueva Contraseña" autocomplete="new-password" required name="password"> <br> <p></p>
    <input type="email" placeholder="Email" autocomplete="email" value="{{ request.user.email }}" name="email"> <br><p></p>
    <input class="form-boton" type="submit" value="Actualizar">  <br><p></p>  
    <br><p></p>            
</form>
{% endblock %}

pagina_web/app/templates/app/Consul_Lista_Individuos_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block title %} Consulta Individuos {% endblock %}


{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/Consul_Lista_Indivios.css' %}">
{% endblock %}

{% block main %}
<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=6 >Consultar lista de Individuos</td>
        <tr>
            <th>Apellidos</th>
            <th>Nombres</th>
            <th>Ultimo partido afiliado</th>
            <th>Total procesos</th>
            <th>Aprobados</th>  
            <th>Consulta</th>                   
        </tr>
    </thead>
    <tbody>
       {% for listas in lista %}
        <tr>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Nombre }}</a></td>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Apellidos }}</a></td>
            <td>Verdes</td>
            <td>15</td>
            <td>✔</td>
            <td><a href="Consultar_Individuo_Admin.html">🔎</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

pagina_web/app/templates/app/Consultar_PartidoP_Usuario.htm
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block title %} Consulta Partido {% endblock %}

{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/Consul_PartidoP_Usu.css' %}">
{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Proceso_Admin_Post' %}" method="POST"></form>
{% csrf_token %}
<table class="table-proceso">            
    <thead>
        <td class="table_titulo" COLSPAN=2 >Procesos para partido: Partido Nombre </td>
        <tr>
            <th class="table-proceso-item">Total</th>
            <th class="table-proceso-item">Culpables</th>
        </tr>
</thead>



<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=6 >Lista de afiliados</td>
        <tr>
            <th>Apellidos</th>
            <th>Nombres</th>
            <th>Fecha de ingreso</th>
            <th>Fecha de salida</th>
                             
        </tr>
    </thead>
    <tbody>
       {% for listas in lista %}
        <tr>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Nombre }}</a></td>
            <td><a href="Consultar_Individuo_Admin.html">{{ listas.Apellidos }}</a></td>
            <td>a </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
</form>
{% endblock %}

pagina_web/app/templates/app/Crear_Indivduo_Exito_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Crear Individuo{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">🟢 INDIVIDUO CREADO CON EXITO 🟢</h1>    
</div>

{% endblock %}

pagina_web/app/templates/app/Crear_Individuo_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}

{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/Crear_individuo.css' %}">
    
{% endblock %}


{% block title %}Crear Individuo{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Individuo_Admin_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Crear Individuo</h1>
    <label for="">Apellidos</label>
    <input type="text" placeholder="Apellidos" name="Apellidos" id="Apellidos" required> <br> <p></p>
    <label for="">Nombre</label>
    <input type="text" placeholder="Nombres" name="Nombres" id="Nombre" required> <br> <p></p>
    <label for="">Fecha de Nacimiento</label>
    <input type="date" placeholder="Fecha de Nacimiento" name="Fecha de Nacimiento"  id="Fecha">
    <input class="form-boton" type="submit" value="Crear"> <p></p>  
    <br><p></p>            
</form>
{% endblock %}

pagina_web/app/templates/app/Crear_Partido_Politico.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Partido_politico_Admin.css' %}">
{% endblock %}

{% block title %}Crear partido político{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Partido_Politico_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Crear partido político</h1>
    <label for="">Nombre del partido politico</label>
    <input type="text" placeholder="Partido Político"  autocomplete="given-name" name="partido" required> <br> <p></p>
    <input class="form-boton" type="submit" value="Crear">  <br><p></p>  
    <br><p></p>            
</form>
{% endblock %}

pagina_web/app/templates/app/Crear_Proceso_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}


{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/crear_proceso_admin.css' %}">
{% endblock %}

{% block title %}Crear Proceso{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Proceso_Admin_Post' %}" method="POST">
    {% csrf_token %}
    <h1>Crear Proceso</h1>
            <label for="">Título</label>
            <input type="text" placeholder="Título"  name="titulo" id="titulo"> <br> <br>
            <label for="" id="F_Inicio">Fecha de Inicio</label>
            <input type="date" name="F_Inicio"> <br> <br>
            <label for="" id="F_Fin">Fecha de Finalización</label>
            <input type="date" name="F_Fin"> <br> <br>
            <label for="">Abierto</label>
            <input type="checkbox" name="abierto" id="abierto"> <br> <br>
            <label for="">Entidad</label>
            <input type="text" placeholder="Entidad" name="entidad" id="entidad"> <br> <br>
            <label for="">Monto</label>
            <input type="text" placeholder="$" name="monto" id="monto"> <br> <br>
            <label for="" >Comentarios</label><br>
            <textarea name="comentarios" id="comentarios" placeholder="Escriba sus comentarios aquí" ></textarea><br>
            <input class="form-boton" type="submit" value="Crear"> <br>
                      
</form>
{% endblock %}

pagina_web/app/templates/app/Crear_Proceso_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}


{% block extra_head %}    
    <link rel="stylesheet" href="{% static 'app/crear_proceso_admin.css' %}">
{% endblock %}

{% block title %}Crear Proceso{% endblock %}

{% block main %}
<form action="{% url 'app:Crear_Proceso_Usu_Post' request.user.id %}" method="POST">
    {% csrf_token %}
    <h1>Crear Proceso</h1>
            <label for="">Título</label>
            <input type="text" placeholder="Título"  name="titulo" id="titulo"> <br> <br>
            <label for="" id="F_Inicio">Fecha de Inicio</label>
            <input type="date" name="F_Inicio"> <br> <br>
            <label for="" id="F_Fin">Fecha de Finalización</label>
            <input type="date" name="F_Fin"> <br> <br>
            <label for="">Abierto</label>
            <input type="checkbox" name="abierto" id="abierto"> <br> <br>
            <label for="">Entidad</label>
            <input type="text" placeholder="Entidad" name="entidad" id="entidad"> <br> <br>
            <label for="">Monto</label>
            <input type="text" placeholder="$" name="monto" id="monto"> <br> <br>
            <label for="" >Comentarios</label><br>
            <textarea name="comentarios" id="comentarios" placeholder="Escriba sus comentarios aquí" ></textarea><br>
            <input class="form-boton" type="submit" value="Crear">  <br>
            <br>            
</form>
{% endblock %}

pagina_web/app/templates/app/Lista_Individuos_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Consul_Lista_Indivios.css' %}">
{% endblock %}

{% block title %}Lista de Individuos{% endblock %}

{% block main %}
<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=6 >Lista de Individuos</td>
        <tr>
            <th>Apellidos</th>
            <th>Nombre</th>
            <th>Ultimo partido afiliado</th>
            <th>Total procesos</th>
            <th>Consulta</th>                   
            </tr>
    </thead>
    <tbody>
        {% for L in listas %}
        
        <tr>
            <td><a href="#"> {{ L.apellidos }}  </a></td>
            <td><a href="#"> {{ L.nombres }}  </a></td>
            <td> {{L.partido}} </td>
            <td>0</td> <!-- Toltal procesos -->
            <td><a href="#">🔎</a></td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>

{% endblock %}

pagina_web/app/templates/app/Lista_Partidos_Admin.html
{% extends "app/Pag_Admin_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Consul_Lista_Indivios.css' %}">
{% endblock %}

{% block title %}Lista partidos políticos{% endblock %}

{% block main %}
<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=4 >Lista de partidos politicos</td>
        <tr>
            <th>Nombre partido</th>
            <th>Total visitas</th>
            <th>Total procesos</th> 
            <th>Consulta</th>                   
            </tr>
    </thead>
    <tbody>

        {% for L in listas %}
        <tr>
            <td><a href="#"> {{ L.nombre }}  </a></td>
            <td> {{L.visitas}} </td>
            <td>0</td> <!-- Toltal procesos -->
            <td><a href="#">🔎</a></td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>

{% endblock %}

pagina_web/app/templates/app/Lista_Partidos_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'app/Consul_Lista_Indivios.css' %}">
{% endblock %}

{% block title %}Lista partidos políticos{% endblock %}

{% block main %}
<table>
            
    <thead>
        
        <td class="table_titulo" COLSPAN=4 >Lista de partidos politicos</td>
        <tr>
            <th>Nombre partido</th>
            <th>Total visitas</th>
            <th>Total procesos</th> 
            <th>Consulta</th>                   
            </tr>
    </thead>
    <tbody>

        {% for L in listas %}
        <tr>
            <td><a href="#"> {{ L.nombre }}  </a></td>
            <td> {{L.visitas}} </td>
            <td>0</td> <!-- Toltal procesos -->
            <td><a href="#">🔎</a></td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>

{% endblock %}

pagina_web/app/templates/app/UsuActu_Error_Usu.html
{% extends "app/Pag_Usuario_Style.html" %}
{% load static %}
{% block extra_head %}

{% endblock %}

{% block title %}Actualizar Datos{% endblock %}

{% block main %}
<div style="margin-top: 350px">
    <h1 style="text-align:center">ERROR, CUENTA SIN ACTUALIZAR </h1>
    <h2 style="text-align:center">🔴 Intente nuevamente con un usuario o correo diferente 🔴</h2>
</div>

{% endblock %}

pagina_web/app/templates/app/UsuCreado_Error.html
{% extends "app/index.html" %}

{% block info %}
<h1>🚨 REGISTRO FALLIDO 🚨</h1>
<h2 style="text-align:center">🔴 Intente nuevamente con un usuario o correo diferente 🔴</h2>
{% endblock %}